### ISSUE TITLE
使用yolov5模型时界面闪退

### ISSUE THREAD

**Issue by xiaohui0225** [zhuyuliang/labelGo-YoloAutoLabelImg#1]
在选择yolov5的.pt文件之后就会闪退，您遇到过吗？yolov7是可以使用的。

**Comment by zhuyuliang** [comment]
感谢支持，yolov5问题已修复，目前不能一次打开同时两个自动标注切换执行，需要关闭后重新打开才能用另一个模型。这个问题后期会修复。

**Comment by xiaohui0225** [comment]
大佬您好，请问模型切换的bug解决了吗？我尝试了好久都没能解决。

**Comment by zhuyuliang** [comment]
还没处理，打开状态下还不能切换模型，需要重新打开切换v5和v7
